// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6JQux0e7fPUSD7nQGdEDQv1-LE-rOWdg',
    appId: '1:912883226091:web:2f00fa1274ef07570f75ae',
    messagingSenderId: '912883226091',
    projectId: 'babyshop-c2133',
    authDomain: 'babyshop-c2133.firebaseapp.com',
    storageBucket: 'babyshop-c2133.firebasestorage.app',
    measurementId: 'G-65C289KR42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWQccMfOGls5CEJGr96Vzipe1lgNuEkhA',
    appId: '1:912883226091:android:78803185f80878690f75ae',
    messagingSenderId: '912883226091',
    projectId: 'babyshop-c2133',
    storageBucket: 'babyshop-c2133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9qBRAsqQRMrzz8T9BT2Afy7qeFAKw9nE',
    appId: '1:912883226091:ios:d7402ff668eb64820f75ae',
    messagingSenderId: '912883226091',
    projectId: 'babyshop-c2133',
    storageBucket: 'babyshop-c2133.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9qBRAsqQRMrzz8T9BT2Afy7qeFAKw9nE',
    appId: '1:912883226091:ios:d7402ff668eb64820f75ae',
    messagingSenderId: '912883226091',
    projectId: 'babyshop-c2133',
    storageBucket: 'babyshop-c2133.firebasestorage.app',
    iosBundleId: 'com.example.babyShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6JQux0e7fPUSD7nQGdEDQv1-LE-rOWdg',
    appId: '1:912883226091:web:8642937453682b1c0f75ae',
    messagingSenderId: '912883226091',
    projectId: 'babyshop-c2133',
    authDomain: 'babyshop-c2133.firebaseapp.com',
    storageBucket: 'babyshop-c2133.firebasestorage.app',
    measurementId: 'G-X67BVF6KT1',
  );
}
